/**
 * Mock data — produtos reais da Casa Mr. Lion
 * Usado quando VITE_SUPABASE_URL é placeholder (modo demo)
 *
 * Catálogo: 3 linhas × 3 formatos + acessórios = 10 SKUs
 * Simulação: 60 dias de operação real (jan–mar 2026)
 */

import type { Product, StockMovement, DeliveryOrder } from '@/types'

export const MOCK_PRODUCTS: Product[] = [
  // ── HONEY ───────────────────────────────────────────────────────────────
  // Produto-herói: 65% do volume total
  {
    id: 'honey-sg',
    name: 'Mr. Lion Honey — Só Garrafa',
    sku: 'ML-HONEY-SG',
    category: 'honey',
    current_stock: 42,
    min_stock: 30,
    price_cost: 45,
    price_sale: 89,
    supplier: 'Lamas Destilaria',
    location: 'Galpão A - Prateleira 1',
    active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2026-03-09T00:00:00Z',
  },
  {
    id: 'honey-cmp',
    name: 'Mr. Lion Honey — Completo',
    sku: 'ML-HONEY-CMP',
    category: 'honey',
    current_stock: 18,
    min_stock: 15,
    price_cost: 48,
    price_sale: 95,
    supplier: 'Lamas Destilaria',
    location: 'Galpão A - Prateleira 1',
    active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2026-03-09T00:00:00Z',
  },
  {
    id: 'honey-png',
    name: 'Mr. Lion Honey — Pingente',
    sku: 'ML-HONEY-PNG',
    category: 'honey',
    current_stock: 6,
    min_stock: 10,
    price_cost: 42,
    price_sale: 85,
    supplier: 'Lamas Destilaria',
    location: 'Galpão A - Prateleira 2',
    active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2026-03-09T00:00:00Z',
  },

  // ── CAPPUCCINO ──────────────────────────────────────────────────────────
  // 29% do volume total
  {
    id: 'capu-sg',
    name: 'Mr. Lion Cappuccino — Só Garrafa',
    sku: 'ML-CAPU-SG',
    category: 'cappuccino',
    current_stock: 16,
    min_stock: 20,
    price_cost: 38,
    price_sale: 79,
    supplier: 'Lamas Destilaria',
    location: 'Galpão A - Prateleira 3',
    active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2026-03-09T00:00:00Z',
  },
  {
    id: 'capu-cmp',
    name: 'Mr. Lion Cappuccino — Completo',
    sku: 'ML-CAPU-CMP',
    category: 'cappuccino',
    current_stock: 14,
    min_stock: 10,
    price_cost: 40,
    price_sale: 82,
    supplier: 'Lamas Destilaria',
    location: 'Galpão A - Prateleira 3',
    active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2026-03-09T00:00:00Z',
  },
  {
    id: 'capu-png',
    name: 'Mr. Lion Cappuccino — Pingente',
    sku: 'ML-CAPU-PNG',
    category: 'cappuccino',
    current_stock: 4,
    min_stock: 5,
    price_cost: 36,
    price_sale: 75,
    supplier: 'Lamas Destilaria',
    location: 'Galpão A - Prateleira 4',
    active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2026-03-09T00:00:00Z',
  },

  // ── BLENDED ─────────────────────────────────────────────────────────────
  // Lançado em dez/2025. 4% do volume, 37,5% do CMV
  {
    id: 'blend-sg',
    name: 'Mr. Lion Blended — Só Garrafa',
    sku: 'ML-BLEND-SG',
    category: 'blended',
    current_stock: 22,
    min_stock: 10,
    price_cost: 52,
    price_sale: 105,
    supplier: 'Lamas Destilaria',
    location: 'Galpão B - Prateleira 1',
    active: true,
    created_at: '2025-12-01T00:00:00Z',
    updated_at: '2026-03-09T00:00:00Z',
  },
  {
    id: 'blend-cmp',
    name: 'Mr. Lion Blended — Completo',
    sku: 'ML-BLEND-CMP',
    category: 'blended',
    current_stock: 35,
    min_stock: 15,
    price_cost: 55,
    price_sale: 110,
    supplier: 'Lamas Destilaria',
    location: 'Galpão B - Prateleira 1',
    active: true,
    created_at: '2025-12-01T00:00:00Z',
    updated_at: '2026-03-09T00:00:00Z',
  },
  {
    id: 'blend-png',
    name: 'Mr. Lion Blended — Pingente',
    sku: 'ML-BLEND-PNG',
    category: 'blended',
    current_stock: 2,
    min_stock: 5,
    price_cost: 50,
    price_sale: 99,
    supplier: 'Lamas Destilaria',
    location: 'Galpão B - Prateleira 2',
    active: true,
    created_at: '2025-12-01T00:00:00Z',
    updated_at: '2026-03-09T00:00:00Z',
  },

  // ── ACESSÓRIOS ──────────────────────────────────────────────────────────
  {
    id: 'acesso-copo',
    name: 'Copo Mr. Lion Personalizado',
    sku: 'ML-ACESSO-COPO',
    category: 'acessorio',
    current_stock: 28,
    min_stock: 20,
    price_cost: 8,
    price_sale: 18,
    supplier: 'Fornecedor SP',
    location: 'Depósito - Caixa 1',
    active: true,
    created_at: '2025-06-01T00:00:00Z',
    updated_at: '2026-03-09T00:00:00Z',
  },
]

const uAngelo = { full_name: 'Angelo' }
const uJoao   = { full_name: 'João Lamas' }

// Helper — N dias atrás, com hora opcional (default: meio-dia)
const daysAgo = (n: number, hour = 12): string =>
  new Date(Date.now() - n * 24 * 60 * 60 * 1000 + hour * 60 * 60 * 1000).toISOString()

export const MOCK_MOVEMENTS: StockMovement[] = [
  // ── HOJE (dia 0) ────────────────────────────────────────────────────────
  {
    id: 'mv-01',
    product_id: 'honey-sg',
    action: 'in',
    quantity: 48,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Entrega Lamas Destilaria — lote 0309',
    created_at: daysAgo(0, 9),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uAngelo,
  },
  {
    id: 'mv-02',
    product_id: 'blend-cmp',
    action: 'in',
    quantity: 24,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Entrega Lamas Destilaria — lote 0309',
    created_at: daysAgo(0, 9),
    product: { name: 'Mr. Lion Blended — Completo', sku: 'ML-BLEND-CMP' },
    profile: uAngelo,
  },
  {
    id: 'mv-03',
    product_id: 'honey-sg',
    action: 'out',
    quantity: 12,
    order_id: 'ord-01',
    user_id: 'mock-joao',
    notes: 'Pedido delivery Rio — +55 21 99301-4477',
    created_at: daysAgo(0, 11),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uJoao,
  },
  {
    id: 'mv-04',
    product_id: 'honey-cmp',
    action: 'out',
    quantity: 4,
    order_id: 'ord-01',
    user_id: 'mock-joao',
    notes: 'Pedido delivery Rio — +55 21 99301-4477',
    created_at: daysAgo(0, 11),
    product: { name: 'Mr. Lion Honey — Completo', sku: 'ML-HONEY-CMP' },
    profile: uJoao,
  },
  {
    id: 'mv-05',
    product_id: 'acesso-copo',
    action: 'out',
    quantity: 6,
    order_id: 'ord-02',
    user_id: 'mock-joao',
    notes: 'Prospecção Pedrão — BH (brinde)',
    created_at: daysAgo(0, 14),
    product: { name: 'Copo Mr. Lion Personalizado', sku: 'ML-ACESSO-COPO' },
    profile: uJoao,
  },

  // ── DIA 1 ───────────────────────────────────────────────────────────────
  {
    id: 'mv-06',
    product_id: 'honey-sg',
    action: 'out',
    quantity: 18,
    order_id: 'ord-03',
    user_id: 'mock-joao',
    notes: 'B2B — Bar Degusto RJ (Nível 1)',
    created_at: daysAgo(1, 10),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uJoao,
  },
  {
    id: 'mv-07',
    product_id: 'capu-sg',
    action: 'out',
    quantity: 6,
    order_id: 'ord-03',
    user_id: 'mock-joao',
    notes: 'B2B — Bar Degusto RJ (Nível 1)',
    created_at: daysAgo(1, 10),
    product: { name: 'Mr. Lion Cappuccino — Só Garrafa', sku: 'ML-CAPU-SG' },
    profile: uJoao,
  },
  {
    id: 'mv-08',
    product_id: 'blend-sg',
    action: 'out',
    quantity: 4,
    order_id: 'ord-03',
    user_id: 'mock-joao',
    notes: 'B2B — Bar Degusto RJ (Nível 1)',
    created_at: daysAgo(1, 10),
    product: { name: 'Mr. Lion Blended — Só Garrafa', sku: 'ML-BLEND-SG' },
    profile: uJoao,
  },

  // ── DIA 2 ───────────────────────────────────────────────────────────────
  {
    id: 'mv-09',
    product_id: 'honey-png',
    action: 'adjustment',
    quantity: -2,
    order_id: null,
    user_id: 'mock-joao',
    notes: 'Ajuste inventário pós-evento Barra da Tijuca',
    created_at: daysAgo(2, 16),
    product: { name: 'Mr. Lion Honey — Pingente', sku: 'ML-HONEY-PNG' },
    profile: uJoao,
  },
  {
    id: 'mv-10',
    product_id: 'blend-png',
    action: 'loss',
    quantity: 2,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Perda transporte — embalagem danificada (Correios)',
    created_at: daysAgo(2, 10),
    product: { name: 'Mr. Lion Blended — Pingente', sku: 'ML-BLEND-PNG' },
    profile: uAngelo,
  },
  {
    id: 'mv-11',
    product_id: 'honey-sg',
    action: 'out',
    quantity: 10,
    order_id: 'ord-04',
    user_id: 'mock-angelo',
    notes: 'Delivery Direto RJ — +55 21 98867-2210',
    created_at: daysAgo(2, 13),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uAngelo,
  },

  // ── DIA 3 ───────────────────────────────────────────────────────────────
  {
    id: 'mv-12',
    product_id: 'capu-sg',
    action: 'in',
    quantity: 24,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Reposição estoque — transferência depósito BH',
    created_at: daysAgo(3, 9),
    product: { name: 'Mr. Lion Cappuccino — Só Garrafa', sku: 'ML-CAPU-SG' },
    profile: uAngelo,
  },
  {
    id: 'mv-13',
    product_id: 'honey-sg',
    action: 'out',
    quantity: 8,
    order_id: 'ord-05',
    user_id: 'mock-joao',
    notes: 'Pedrão — BH (prospecção presencial)',
    created_at: daysAgo(3, 15),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uJoao,
  },
  {
    id: 'mv-14',
    product_id: 'honey-cmp',
    action: 'out',
    quantity: 3,
    order_id: 'ord-05',
    user_id: 'mock-joao',
    notes: 'Pedrão — BH (prospecção presencial)',
    created_at: daysAgo(3, 15),
    product: { name: 'Mr. Lion Honey — Completo', sku: 'ML-HONEY-CMP' },
    profile: uJoao,
  },

  // ── DIA 5 ───────────────────────────────────────────────────────────────
  {
    id: 'mv-15',
    product_id: 'honey-sg',
    action: 'in',
    quantity: 36,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Entrega Lamas Destilaria — lote 0304',
    created_at: daysAgo(5, 9),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uAngelo,
  },
  {
    id: 'mv-16',
    product_id: 'capu-cmp',
    action: 'out',
    quantity: 5,
    order_id: 'ord-06',
    user_id: 'mock-joao',
    notes: 'Transferência filial SP — evento corporativo',
    created_at: daysAgo(5, 14),
    product: { name: 'Mr. Lion Cappuccino — Completo', sku: 'ML-CAPU-CMP' },
    profile: uJoao,
  },
  {
    id: 'mv-17',
    product_id: 'blend-cmp',
    action: 'out',
    quantity: 6,
    order_id: 'ord-06',
    user_id: 'mock-joao',
    notes: 'Transferência filial SP — evento corporativo',
    created_at: daysAgo(5, 14),
    product: { name: 'Mr. Lion Blended — Completo', sku: 'ML-BLEND-CMP' },
    profile: uJoao,
  },

  // ── DIA 7 ───────────────────────────────────────────────────────────────
  {
    id: 'mv-18',
    product_id: 'honey-sg',
    action: 'out',
    quantity: 15,
    order_id: 'ord-07',
    user_id: 'mock-joao',
    notes: 'B2B — Café Cervejaria Lagoa RJ (50 un. mensais)',
    created_at: daysAgo(7, 11),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uJoao,
  },
  {
    id: 'mv-19',
    product_id: 'acesso-copo',
    action: 'in',
    quantity: 20,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Reposição copos — fornecedor gráfica Belo Horizonte',
    created_at: daysAgo(7, 9),
    product: { name: 'Copo Mr. Lion Personalizado', sku: 'ML-ACESSO-COPO' },
    profile: uAngelo,
  },
  {
    id: 'mv-20',
    product_id: 'capu-png',
    action: 'adjustment',
    quantity: -1,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Ajuste inventário — diferença contagem física',
    created_at: daysAgo(7, 17),
    product: { name: 'Mr. Lion Cappuccino — Pingente', sku: 'ML-CAPU-PNG' },
    profile: uAngelo,
  },

  // ── DIA 10 ──────────────────────────────────────────────────────────────
  {
    id: 'mv-21',
    product_id: 'honey-sg',
    action: 'out',
    quantity: 20,
    order_id: 'ord-08',
    user_id: 'mock-joao',
    notes: 'B2B — Empório Pinheiros SP (pedido quinzenal)',
    created_at: daysAgo(10, 10),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uJoao,
  },
  {
    id: 'mv-22',
    product_id: 'capu-sg',
    action: 'out',
    quantity: 8,
    order_id: 'ord-08',
    user_id: 'mock-joao',
    notes: 'B2B — Empório Pinheiros SP (pedido quinzenal)',
    created_at: daysAgo(10, 10),
    product: { name: 'Mr. Lion Cappuccino — Só Garrafa', sku: 'ML-CAPU-SG' },
    profile: uJoao,
  },
  {
    id: 'mv-23',
    product_id: 'blend-sg',
    action: 'in',
    quantity: 30,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Entrega Lamas Destilaria — Blended lote 0227',
    created_at: daysAgo(10, 8),
    product: { name: 'Mr. Lion Blended — Só Garrafa', sku: 'ML-BLEND-SG' },
    profile: uAngelo,
  },

  // ── DIA 13 ──────────────────────────────────────────────────────────────
  {
    id: 'mv-24',
    product_id: 'honey-png',
    action: 'in',
    quantity: 12,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Reposição pingentes Honey — estoque regulador',
    created_at: daysAgo(13, 9),
    product: { name: 'Mr. Lion Honey — Pingente', sku: 'ML-HONEY-PNG' },
    profile: uAngelo,
  },
  {
    id: 'mv-25',
    product_id: 'honey-sg',
    action: 'out',
    quantity: 6,
    order_id: 'ord-09',
    user_id: 'mock-joao',
    notes: 'Delivery Direto RJ — +55 21 97723-0091',
    created_at: daysAgo(13, 16),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uJoao,
  },
  {
    id: 'mv-26',
    product_id: 'capu-cmp',
    action: 'loss',
    quantity: 1,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Perda — garrafa quebrada no transporte BH→RJ',
    created_at: daysAgo(13, 11),
    product: { name: 'Mr. Lion Cappuccino — Completo', sku: 'ML-CAPU-CMP' },
    profile: uAngelo,
  },

  // ── DIA 16 ──────────────────────────────────────────────────────────────
  {
    id: 'mv-27',
    product_id: 'honey-sg',
    action: 'in',
    quantity: 60,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Entrega Lamas Destilaria — lote 0221 (maior do mês)',
    created_at: daysAgo(16, 9),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uAngelo,
  },
  {
    id: 'mv-28',
    product_id: 'honey-cmp',
    action: 'in',
    quantity: 18,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Entrega Lamas Destilaria — lote 0221',
    created_at: daysAgo(16, 9),
    product: { name: 'Mr. Lion Honey — Completo', sku: 'ML-HONEY-CMP' },
    profile: uAngelo,
  },
  {
    id: 'mv-29',
    product_id: 'blend-png',
    action: 'in',
    quantity: 10,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Entrega Lamas Destilaria — Blended Pingente primeira remessa',
    created_at: daysAgo(16, 9),
    product: { name: 'Mr. Lion Blended — Pingente', sku: 'ML-BLEND-PNG' },
    profile: uAngelo,
  },

  // ── DIA 18 ──────────────────────────────────────────────────────────────
  {
    id: 'mv-30',
    product_id: 'honey-sg',
    action: 'out',
    quantity: 24,
    order_id: 'ord-10',
    user_id: 'mock-joao',
    notes: 'B2B — Boteco do Léo BH (pedido mensal)',
    created_at: daysAgo(18, 10),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uJoao,
  },
  {
    id: 'mv-31',
    product_id: 'blend-cmp',
    action: 'out',
    quantity: 8,
    order_id: 'ord-10',
    user_id: 'mock-joao',
    notes: 'B2B — Boteco do Léo BH (pedido mensal)',
    created_at: daysAgo(18, 10),
    product: { name: 'Mr. Lion Blended — Completo', sku: 'ML-BLEND-CMP' },
    profile: uJoao,
  },
  {
    id: 'mv-32',
    product_id: 'acesso-copo',
    action: 'out',
    quantity: 10,
    order_id: 'ord-10',
    user_id: 'mock-joao',
    notes: 'B2B — Boteco do Léo BH (brindes cliente)',
    created_at: daysAgo(18, 10),
    product: { name: 'Copo Mr. Lion Personalizado', sku: 'ML-ACESSO-COPO' },
    profile: uJoao,
  },

  // ── DIA 21 ──────────────────────────────────────────────────────────────
  {
    id: 'mv-33',
    product_id: 'capu-sg',
    action: 'in',
    quantity: 30,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Entrega Lamas Destilaria — Capu lote 0216',
    created_at: daysAgo(21, 9),
    product: { name: 'Mr. Lion Cappuccino — Só Garrafa', sku: 'ML-CAPU-SG' },
    profile: uAngelo,
  },
  {
    id: 'mv-34',
    product_id: 'capu-png',
    action: 'in',
    quantity: 8,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Entrega Lamas Destilaria — Capu Pingente lote 0216',
    created_at: daysAgo(21, 9),
    product: { name: 'Mr. Lion Cappuccino — Pingente', sku: 'ML-CAPU-PNG' },
    profile: uAngelo,
  },
  {
    id: 'mv-35',
    product_id: 'honey-sg',
    action: 'adjustment',
    quantity: 3,
    order_id: null,
    user_id: 'mock-joao',
    notes: 'Ajuste inventário — contagem física confirmada supervisor',
    created_at: daysAgo(21, 15),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uJoao,
  },

  // ── DIA 24 ──────────────────────────────────────────────────────────────
  {
    id: 'mv-36',
    product_id: 'honey-sg',
    action: 'out',
    quantity: 30,
    order_id: 'ord-11',
    user_id: 'mock-joao',
    notes: 'B2B — Restaurante Oásis SP (contrato mensal 60 un.)',
    created_at: daysAgo(24, 11),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uJoao,
  },
  {
    id: 'mv-37',
    product_id: 'capu-cmp',
    action: 'out',
    quantity: 4,
    order_id: 'ord-11',
    user_id: 'mock-joao',
    notes: 'B2B — Restaurante Oásis SP',
    created_at: daysAgo(24, 11),
    product: { name: 'Mr. Lion Cappuccino — Completo', sku: 'ML-CAPU-CMP' },
    profile: uJoao,
  },

  // ── DIA 27 ──────────────────────────────────────────────────────────────
  {
    id: 'mv-38',
    product_id: 'honey-sg',
    action: 'in',
    quantity: 48,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Entrega Lamas Destilaria — lote 0210',
    created_at: daysAgo(27, 9),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uAngelo,
  },
  {
    id: 'mv-39',
    product_id: 'blend-cmp',
    action: 'in',
    quantity: 30,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Entrega Lamas Destilaria — Blended lote 0210',
    created_at: daysAgo(27, 9),
    product: { name: 'Mr. Lion Blended — Completo', sku: 'ML-BLEND-CMP' },
    profile: uAngelo,
  },
  {
    id: 'mv-40',
    product_id: 'capu-sg',
    action: 'out',
    quantity: 10,
    order_id: 'ord-12',
    user_id: 'mock-joao',
    notes: 'Delivery Direto RJ — +55 21 96650-1188',
    created_at: daysAgo(27, 13),
    product: { name: 'Mr. Lion Cappuccino — Só Garrafa', sku: 'ML-CAPU-SG' },
    profile: uJoao,
  },
  {
    id: 'mv-41',
    product_id: 'honey-sg',
    action: 'out',
    quantity: 12,
    order_id: 'ord-12',
    user_id: 'mock-joao',
    notes: 'Delivery Direto RJ — +55 21 96650-1188',
    created_at: daysAgo(27, 13),
    product: { name: 'Mr. Lion Honey — Só Garrafa', sku: 'ML-HONEY-SG' },
    profile: uJoao,
  },
  {
    id: 'mv-42',
    product_id: 'blend-png',
    action: 'out',
    quantity: 4,
    order_id: 'ord-13',
    user_id: 'mock-joao',
    notes: 'Prospecção Pedrão — BH (amostras degustação)',
    created_at: daysAgo(27, 16),
    product: { name: 'Mr. Lion Blended — Pingente', sku: 'ML-BLEND-PNG' },
    profile: uJoao,
  },
  {
    id: 'mv-43',
    product_id: 'honey-cmp',
    action: 'out',
    quantity: 6,
    order_id: 'ord-13',
    user_id: 'mock-joao',
    notes: 'Prospecção Pedrão — BH (amostras degustação)',
    created_at: daysAgo(27, 16),
    product: { name: 'Mr. Lion Honey — Completo', sku: 'ML-HONEY-CMP' },
    profile: uJoao,
  },
  {
    id: 'mv-44',
    product_id: 'acesso-copo',
    action: 'in',
    quantity: 24,
    order_id: null,
    user_id: 'mock-angelo',
    notes: 'Reposição copos — segundo lote gráfica BH',
    created_at: daysAgo(27, 8),
    product: { name: 'Copo Mr. Lion Personalizado', sku: 'ML-ACESSO-COPO' },
    profile: uAngelo,
  },
]

export const MOCK_ORDERS: DeliveryOrder[] = [
  // ── PEDIDOS CONFIRMADOS (hoje / últimos 2 dias) ──────────────────────────
  {
    id: 'ord-01',
    items: [
      { product_id: 'honey-sg',  product_name: 'Mr. Lion Honey — Só Garrafa', quantity: 12, unit_price: 89 },
      { product_id: 'honey-cmp', product_name: 'Mr. Lion Honey — Completo',    quantity: 4,  unit_price: 95 },
    ],
    status: 'confirmed',
    user_id: 'mock-joao',
    notes: null,
    reference: '+55 21 99301-4477',
    address: 'Rua Visconde de Pirajá, 414, Ipanema, Rio de Janeiro - RJ',
    total_value: 12 * 89 + 4 * 95,
    delivered_by: null,
    delivered_at: null,
    created_at: daysAgo(0, 11),
    profile: uJoao,
  },
  {
    id: 'ord-02',
    items: [
      { product_id: 'acesso-copo', product_name: 'Copo Mr. Lion Personalizado', quantity: 6, unit_price: 18 },
      { product_id: 'honey-sg',    product_name: 'Mr. Lion Honey — Só Garrafa', quantity: 4, unit_price: 89 },
    ],
    status: 'confirmed',
    user_id: 'mock-joao',
    notes: 'Levar copos no encontro presencial',
    reference: 'Pedrão — BH',
    address: 'Av. do Contorno, 2905, Santo Antônio, Belo Horizonte - MG',
    total_value: 6 * 18 + 4 * 89,
    delivered_by: null,
    delivered_at: null,
    created_at: daysAgo(0, 14),
    profile: uJoao,
  },
  {
    id: 'ord-03',
    items: [
      { product_id: 'honey-sg', product_name: 'Mr. Lion Honey — Só Garrafa',      quantity: 18, unit_price: 89  },
      { product_id: 'capu-sg',  product_name: 'Mr. Lion Cappuccino — Só Garrafa', quantity: 6,  unit_price: 79  },
      { product_id: 'blend-sg', product_name: 'Mr. Lion Blended — Só Garrafa',    quantity: 4,  unit_price: 105 },
    ],
    status: 'confirmed',
    user_id: 'mock-joao',
    notes: 'B2B Nível 1 — 30 dias de prazo',
    reference: 'Bar Degusto RJ',
    address: 'Rua Dias Ferreira, 636, Leblon, Rio de Janeiro - RJ',
    total_value: 18 * 89 + 6 * 79 + 4 * 105,
    delivered_by: null,
    delivered_at: null,
    created_at: daysAgo(1, 10),
    profile: uJoao,
  },

  // ── PEDIDOS ENTREGUES (últimas 2 semanas) ───────────────────────────────
  {
    id: 'ord-04',
    items: [
      { product_id: 'honey-sg', product_name: 'Mr. Lion Honey — Só Garrafa', quantity: 10, unit_price: 89 },
    ],
    status: 'delivered',
    user_id: 'mock-angelo',
    notes: null,
    reference: '+55 21 98867-2210',
    address: 'Rua Barata Ribeiro, 370, Copacabana, Rio de Janeiro - RJ',
    total_value: 10 * 89,
    delivered_by: 'Angelo',
    delivered_at: daysAgo(2, 16),
    created_at: daysAgo(2, 13),
    profile: uAngelo,
  },
  {
    id: 'ord-05',
    items: [
      { product_id: 'honey-sg',  product_name: 'Mr. Lion Honey — Só Garrafa', quantity: 8, unit_price: 89 },
      { product_id: 'honey-cmp', product_name: 'Mr. Lion Honey — Completo',    quantity: 3, unit_price: 95 },
    ],
    status: 'delivered',
    user_id: 'mock-joao',
    notes: 'Prospecção presencial — cliente muito interessado em contrato B2B',
    reference: 'Pedrão — BH',
    address: 'Av. Raja Gabaglia, 1252, Gutierrez, Belo Horizonte - MG',
    total_value: 8 * 89 + 3 * 95,
    delivered_by: 'João Lamas',
    delivered_at: daysAgo(3, 18),
    created_at: daysAgo(3, 15),
    profile: uJoao,
  },
  {
    id: 'ord-06',
    items: [
      { product_id: 'capu-cmp',  product_name: 'Mr. Lion Cappuccino — Completo', quantity: 5, unit_price: 82  },
      { product_id: 'blend-cmp', product_name: 'Mr. Lion Blended — Completo',    quantity: 6, unit_price: 110 },
    ],
    status: 'delivered',
    user_id: 'mock-joao',
    notes: 'Evento corporativo patrocinado — 150 pessoas',
    reference: 'Transferência filial SP',
    address: 'Av. Paulista, 1106, Bela Vista, São Paulo - SP',
    total_value: 5 * 82 + 6 * 110,
    delivered_by: 'Angelo',
    delivered_at: daysAgo(5, 17),
    created_at: daysAgo(5, 14),
    profile: uJoao,
  },
  {
    id: 'ord-07',
    items: [
      { product_id: 'honey-sg', product_name: 'Mr. Lion Honey — Só Garrafa', quantity: 15, unit_price: 89 },
    ],
    status: 'delivered',
    user_id: 'mock-joao',
    notes: 'Contrato 50 un./mês — segunda quinzena',
    reference: 'Café Cervejaria Lagoa RJ',
    address: 'Av. Epitácio Pessoa, 1674, Lagoa, Rio de Janeiro - RJ',
    total_value: 15 * 89,
    delivered_by: 'João Lamas',
    delivered_at: daysAgo(7, 14),
    created_at: daysAgo(7, 11),
    profile: uJoao,
  },
  {
    id: 'ord-08',
    items: [
      { product_id: 'honey-sg', product_name: 'Mr. Lion Honey — Só Garrafa',      quantity: 20, unit_price: 89 },
      { product_id: 'capu-sg',  product_name: 'Mr. Lion Cappuccino — Só Garrafa', quantity: 8,  unit_price: 79 },
    ],
    status: 'delivered',
    user_id: 'mock-joao',
    notes: 'Pedido quinzenal — entregar terça-feira',
    reference: 'Empório Pinheiros SP',
    address: 'Rua Teodoro Sampaio, 1020, Pinheiros, São Paulo - SP',
    total_value: 20 * 89 + 8 * 79,
    delivered_by: 'Angelo',
    delivered_at: daysAgo(10, 13),
    created_at: daysAgo(10, 10),
    profile: uJoao,
  },
  {
    id: 'ord-09',
    items: [
      { product_id: 'honey-sg', product_name: 'Mr. Lion Honey — Só Garrafa', quantity: 6, unit_price: 89 },
    ],
    status: 'delivered',
    user_id: 'mock-joao',
    notes: null,
    reference: '+55 21 97723-0091',
    address: 'Rua Jardim Botânico, 508, Jardim Botânico, Rio de Janeiro - RJ',
    total_value: 6 * 89,
    delivered_by: 'João Lamas',
    delivered_at: daysAgo(13, 19),
    created_at: daysAgo(13, 16),
    profile: uJoao,
  },
  {
    id: 'ord-10',
    items: [
      { product_id: 'honey-sg',    product_name: 'Mr. Lion Honey — Só Garrafa',  quantity: 24, unit_price: 89  },
      { product_id: 'blend-cmp',   product_name: 'Mr. Lion Blended — Completo',  quantity: 8,  unit_price: 110 },
      { product_id: 'acesso-copo', product_name: 'Copo Mr. Lion Personalizado',   quantity: 10, unit_price: 18  },
    ],
    status: 'delivered',
    user_id: 'mock-joao',
    notes: 'Pedido mensal com brindes',
    reference: 'Boteco do Léo BH',
    address: 'Rua Sergipe, 1234, Savassi, Belo Horizonte - MG',
    total_value: 24 * 89 + 8 * 110 + 10 * 18,
    delivered_by: 'João Lamas',
    delivered_at: daysAgo(18, 13),
    created_at: daysAgo(18, 10),
    profile: uJoao,
  },
  {
    id: 'ord-11',
    items: [
      { product_id: 'honey-sg',  product_name: 'Mr. Lion Honey — Só Garrafa',    quantity: 30, unit_price: 89 },
      { product_id: 'capu-cmp',  product_name: 'Mr. Lion Cappuccino — Completo',  quantity: 4,  unit_price: 82 },
    ],
    status: 'delivered',
    user_id: 'mock-joao',
    notes: 'Contrato mensal 60 un. — primeira parcela',
    reference: 'Restaurante Oásis SP',
    address: 'Al. Santos, 2224, Jardim Paulista, São Paulo - SP',
    total_value: 30 * 89 + 4 * 82,
    delivered_by: 'Angelo',
    delivered_at: daysAgo(24, 14),
    created_at: daysAgo(24, 11),
    profile: uJoao,
  },
  {
    id: 'ord-12',
    items: [
      { product_id: 'honey-sg', product_name: 'Mr. Lion Honey — Só Garrafa',      quantity: 12, unit_price: 89 },
      { product_id: 'capu-sg',  product_name: 'Mr. Lion Cappuccino — Só Garrafa', quantity: 10, unit_price: 79 },
    ],
    status: 'delivered',
    user_id: 'mock-joao',
    notes: null,
    reference: '+55 21 96650-1188',
    address: 'Rua Humaitá, 275, Humaitá, Rio de Janeiro - RJ',
    total_value: 12 * 89 + 10 * 79,
    delivered_by: 'João Lamas',
    delivered_at: daysAgo(27, 16),
    created_at: daysAgo(27, 13),
    profile: uJoao,
  },
  {
    id: 'ord-13',
    items: [
      { product_id: 'blend-png', product_name: 'Mr. Lion Blended — Pingente', quantity: 4, unit_price: 99 },
      { product_id: 'honey-cmp', product_name: 'Mr. Lion Honey — Completo',    quantity: 6, unit_price: 95 },
    ],
    status: 'delivered',
    user_id: 'mock-joao',
    notes: 'Amostras para degustação — follow-up em 7 dias',
    reference: 'Prospecção Pedrão — BH',
    address: 'Rua da Bahia, 1148, Lourdes, Belo Horizonte - MG',
    total_value: 4 * 99 + 6 * 95,
    delivered_by: 'João Lamas',
    delivered_at: daysAgo(27, 19),
    created_at: daysAgo(27, 16),
    profile: uJoao,
  },
]
